In [117]:
import pandas as pd
import numpy as np

In [118]:
freq=pd.read_csv(r'C:\Users\LENOVO\Downloads\archive_i\freMTPLfreq.csv')
sev=pd.read_csv(r'C:\Users\LENOVO\Downloads\archive_i\freMTPLsev.csv')

In [119]:
freq.shape,sev.shape

((413169, 10), (16181, 2))

In [120]:
freq.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 413169 entries, 0 to 413168
Data columns (total 10 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   PolicyID   413169 non-null  int64
 1   ClaimNb    413169 non-null  int64
 2   Exposure   413169 non-null  float64
 3   Power      413169 non-null  object
 4   CarAge     413169 non-null  int64
 5   DriverAge  413169 non-null  int64
 6   Brand      413169 non-null  object
 7   Gas        413169 non-null  object
 8   Region     413169 non-null  object
 9   Density    413169 non-null  int64
dtypes: float64(1), int64(5), object(4)
memory usage: 31.5+ MB

In [121]:
freq['PolicyID'].duplicated().sum()

0

In [122]:
sev.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16181 entries, 0 to 16180
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PolicyID     16181 non-null  int64
 1   ClaimAmount  16181 non-null  int64
dtypes: int64(2)
memory usage: 253.0 KB

In [123]:
sum(sev['ClaimAmount'])

34465077

In [124]:
sev.head()

   PolicyID  ClaimAmount
0     63987         1172
1    310037         1905
2    314463         1150
3    318713         1220
4    309380        55077

In [125]:
# Aggregate the claim amounts by PolicyID, prior to merging MTPLfreq with MTPLsev.

MTPLsev_grp = sev.groupby(['PolicyID'])[['ClaimAmount']].agg('sum').reset_index()

In [126]:
MTPLsev_grp.shape

(15390, 2)

In [127]:
df_merged = pd.merge(freq, MTPLsev_grp, how='outer', on='PolicyID').fillna(0).set_index('PolicyID')

In [128]:
df_merged.head()

,ClaimNb,Exposure,Power,CarAge,DriverAge,Brand,Gas,Region,Density,ClaimAmount
PolicyID,,,,,,,,,,
1,0,0.09,g,0,46,Japanese (except Nissan) or Korean,Diesel,Aquitaine,76,0.0
2,0,0.84,g,0,46,Japanese (except Nissan) or Korean,Diesel,Aquitaine,76,0.0
3,0,0.52,f,2,38,Japanese (except Nissan) or Korean,Regular,Nord-Pas-de-Calais,3003,0.0
4,0,0.45,f,2,38,Japanese (except Nissan) or Korean,Regular,Nord-Pas-de-Calais,3003,0.0
5,0,0.15,g,0,41,Japanese (except Nissan) or Korean,Diesel,Pays-de-la-Loire,60,0.0

In [129]:
df_merged['ClaimAmount'].sum()

34465077.0

In [130]:
print(df_merged.columns)
print('\n')
print(df_merged.dtypes)
print('\n')

Index(['ClaimNb', 'Exposure', 'Power', 'CarAge', 'DriverAge', 'Brand', 'Gas',
       'Region', 'Density', 'ClaimAmount'],
      dtype='object')


ClaimNb          int64
Exposure       float64
Power           object
CarAge           int64
DriverAge        int64
Brand           object
Gas             object
Region          object
Density          int64
ClaimAmount    float64
dtype: object

In [131]:
df_merged.head()

,ClaimNb,Exposure,Power,CarAge,DriverAge,Brand,Gas,Region,Density,ClaimAmount
PolicyID,,,,,,,,,,
1,0,0.09,g,0,46,Japanese (except Nissan) or Korean,Diesel,Aquitaine,76,0.0
2,0,0.84,g,0,46,Japanese (except Nissan) or Korean,Diesel,Aquitaine,76,0.0
3,0,0.52,f,2,38,Japanese (except Nissan) or Korean,Regular,Nord-Pas-de-Calais,3003,0.0
4,0,0.45,f,2,38,Japanese (except Nissan) or Korean,Regular,Nord-Pas-de-Calais,3003,0.0
5,0,0.15,g,0,41,Japanese (except Nissan) or Korean,Diesel,Pays-de-la-Loire,60,0.0

In [132]:
policies_no_claims = len(df_merged.loc[df_merged['ClaimNb'] == 0].index)
all_policies = len(df_merged.index)

pct_pols_no_clm = round((policies_no_claims/all_policies)*100, 2) 

print(str(pct_pols_no_clm)+"% of policyholders have not made any claims.")

96.28% of policyholders have not made any claims.

In [179]:
df_merged[df_merged['ClaimAmount']!=0]

,ClaimNb,Exposure,Power,CarAge,DriverAge,Brand,Gas,Region,Density,ClaimAmount,ClaimFreq
PolicyID,,,,,,,,,,,
33,1,0.75,g,1,61,Japanese (except Nissan) or Korean,Regular,Ile-de-France,27000,302.0,1.333333
41,1,0.14,l,5,50,Japanese (except Nissan) or Korean,Diesel,Basse-Normandie,56,2001.0,7.142857
92,1,0.14,d,0,36,Japanese (except Nissan) or Korean,Regular,Ile-de-France,4792,1449.0,7.142857
96,2,0.62,j,0,51,Japanese (except Nissan) or Korean,Regular,Ile-de-France,27000,10870.0,3.225806
142,1,0.75,e,0,34,Japanese (except Nissan) or Korean,Regular,Nord-Pas-de-Calais,1565,1390.0,1.333333
...,...,...,...,...,...,...,...,...,...,...,...
412262,1,0.42,g,1,72,Japanese (except Nissan) or Korean,Diesel,Aquitaine,123,1426.0,2.380952
412270,1,0.36,g,1,53,Japanese (except Nissan) or Korean,Diesel,Nord-Pas-de-Calais,4540,1364.0,2.777778
412664,1,0.22,h,0,34,Japanese (except Nissan) or Korean,Regular,Ile-de-France,6570,7603.0,4.545455
412926,1,0.14,g,2,51,Japanese (except Nissan) or Korean,Diesel,Aquitaine,178,1751.0,7.142857
412944,2,0.17,o,3,36,Japanese (except Nissan) or Korean,Regular,Poitou-Charentes,181,12491.0,11.764706

In [133]:
df_merged['ClaimFreq'] = df_merged['ClaimNb'] / df_merged['Exposure']

In [134]:
df_merged.columns

Index(['ClaimNb', 'Exposure', 'Power', 'CarAge', 'DriverAge', 'Brand', 'Gas',
       'Region', 'Density', 'ClaimAmount', 'ClaimFreq'],
      dtype='object')

In [135]:
data=df_merged.copy()

In [136]:
data

,ClaimNb,Exposure,Power,CarAge,DriverAge,Brand,Gas,Region,Density,ClaimAmount,ClaimFreq
PolicyID,,,,,,,,,,,
1,0,0.090000,g,0,46,Japanese (except Nissan) or Korean,Diesel,Aquitaine,76,0.0,0.0
2,0,0.840000,g,0,46,Japanese (except Nissan) or Korean,Diesel,Aquitaine,76,0.0,0.0
3,0,0.520000,f,2,38,Japanese (except Nissan) or Korean,Regular,Nord-Pas-de-Calais,3003,0.0,0.0
4,0,0.450000,f,2,38,Japanese (except Nissan) or Korean,Regular,Nord-Pas-de-Calais,3003,0.0,0.0
5,0,0.150000,g,0,41,Japanese (except Nissan) or Korean,Diesel,Pays-de-la-Loire,60,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
413165,0,0.002740,j,0,29,Japanese (except Nissan) or Korean,Diesel,Ile-de-France,2471,0.0,0.0
413166,0,0.005479,d,0,29,Japanese (except Nissan) or Korean,Regular,Ile-de-France,5360,0.0,0.0
413167,0,0.005479,k,0,49,Japanese (except Nissan) or Korean,Diesel,Ile-de-France,5360,0.0,0.0
413168,0,0.002740,d,0,41,Japanese (except Nissan) or Korean,Regular,Ile-de-France,9850,0.0,0.0
413169,0,0.002740,g,6,29,Japanese (except Nissan) or Korean,Diesel,Aquitaine,65,0.0,0.0

In [137]:
cat=data.columns[data.dtypes=="object"]
num=data.columns[data.dtypes!="object"]

In [138]:
cat

Index(['Power', 'Brand', 'Gas', 'Region'], dtype='object')

In [139]:
num

Index(['ClaimNb', 'Exposure', 'CarAge', 'DriverAge', 'Density', 'ClaimAmount',
       'ClaimFreq'],
      dtype='object')

In [140]:
for i in cat:
    print(data[i].value_counts())
    print(len(data[i].value_counts()))
    print("====================")

Power
f    95718
g    91198
e    77022
d    68014
h    26698
j    18038
i    17616
k     9537
l     4681
m     1832
o     1508
n     1307
Name: count, dtype: int64
12
====================
Brand
Renault, Nissan or Citroen            218200
Japanese (except Nissan) or Korean     79060
Opel, General Motors or Ford           37402
Volkswagen, Audi, Skoda or Seat        32638
Mercedes, Chrysler or BMW              19280
Fiat                                   16723
other                                   9866
Name: count, dtype: int64
7
====================
Gas
Regular    207224
Diesel     205945
Name: count, dtype: int64
2
====================
Region
Centre                160601
Ile-de-France          69791
Bretagne               42122
Pays-de-la-Loire       38751
Aquitaine              31329
Nord-Pas-de-Calais     27285
Poitou-Charentes       19046
Basse-Normandie        10893
Haute-Normandie         8784
Limousin                4567
Name: count, dtype: int64
10
====================

In [141]:
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder,LabelEncoder,OneHotEncoder # Ordinal Encoding
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler

In [142]:
X=data.drop(labels=['ClaimAmount'],axis=1)
y=data['ClaimAmount']

In [143]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 413169 entries, 1 to 413169
Data columns (total 10 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   ClaimNb    413169 non-null  int64
 1   Exposure   413169 non-null  float64
 2   Power      413169 non-null  object
 3   CarAge     413169 non-null  int64
 4   DriverAge  413169 non-null  int64
 5   Brand      413169 non-null  object
 6   Gas        413169 non-null  object
 7   Region     413169 non-null  object
 8   Density    413169 non-null  int64
 9   ClaimFreq  413169 non-null  float64
dtypes: float64(2), int64(4), object(4)
memory usage: 34.7+ MB

In [144]:
cat_cols=X.select_dtypes(include="object").columns
num_cols=X.select_dtypes(exclude="object").columns

In [145]:
cat_cols

Index(['Power', 'Brand', 'Gas', 'Region'], dtype='object')

In [146]:
num_cols

Index(['ClaimNb', 'Exposure', 'CarAge', 'DriverAge', 'Density', 'ClaimFreq'], dtype='object')

In [147]:
num_pipeline=Pipeline (
    steps=[
        ("imputer",SimpleImputer()),
        ("scaler",MinMaxScaler())
    ]
)

In [148]:
power_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("ordinalencoder", OrdinalEncoder()),
    ("scaler",MinMaxScaler())
])

# Define the preprocessing steps for 'Brand', 'Gas', 'Region' columns
other_cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown='ignore', sparse_output=False)),
    ("scaler",MinMaxScaler())
])

In [149]:
preprocessor=ColumnTransformer(
    [
        ("num_pipeline",num_pipeline,num_cols),
        ("power_pipeline",power_pipeline,['Power']),
        ("other_cat_pipeline",other_cat_pipeline,['Brand', 'Gas', 'Region'])
    ]
)

In [150]:
type(preprocessor)

sklearn.compose._column_transformer.ColumnTransformer

In [151]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.8, test_size=0.2, random_state=1)

In [152]:
preprocessor.fit_transform(X_train)

array([[0.        , 0.24016279, 0.07      , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.50182858, 0.13      , ..., 0.        , 0.        ,
        0.        ],
       [0.25      , 0.19990651, 0.09      , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.18984244, 0.01      , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.08920175, 0.12      , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.50182858, 0.01      , ..., 0.        , 0.        ,
        0.        ]])

In [153]:
preprocessor.transform(X_test)

array([[0.        , 0.08416971, 0.11      , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.50182858, 0.09      , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.38105975, 0.05      , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.50182858, 0.12      , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.0388814 , 0.05      , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.11939396, 0.12      , ..., 1.        , 0.        ,
        0.        ]])

In [154]:
preprocessor.get_feature_names_out()

array(['num_pipeline__ClaimNb', 'num_pipeline__Exposure',
       'num_pipeline__CarAge', 'num_pipeline__DriverAge',
       'num_pipeline__Density', 'num_pipeline__ClaimFreq',
       'power_pipeline__Power', 'other_cat_pipeline__Brand_Fiat',
       'other_cat_pipeline__Brand_Japanese (except Nissan) or Korean',
       'other_cat_pipeline__Brand_Mercedes, Chrysler or BMW',
       'other_cat_pipeline__Brand_Opel, General Motors or Ford',
       'other_cat_pipeline__Brand_Renault, Nissan or Citroen',
       'other_cat_pipeline__Brand_Volkswagen, Audi, Skoda or Seat',
       'other_cat_pipeline__Brand_other',
       'other_cat_pipeline__Gas_Diesel',
       'other_cat_pipeline__Gas_Regular',
       'other_cat_pipeline__Region_Aquitaine',
       'other_cat_pipeline__Region_Basse-Normandie',
       'other_cat_pipeline__Region_Bretagne',
       'other_cat_pipeline__Region_Centre',
       'other_cat_pipeline__Region_Haute-Normandie',
       'other_cat_pipeline__Region_Ile-de-France',
       'other_cat_pipeline__Region_Limousin',
       'other_cat_pipeline__Region_Nord-Pas-de-Calais',
       'other_cat_pipeline__Region_Pays-de-la-Loire',
       'other_cat_pipeline__Region_Poitou-Charentes'], dtype=object)

In [155]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [156]:
X_train.head()

,num_pipeline__ClaimNb,num_pipeline__Exposure,num_pipeline__CarAge,num_pipeline__DriverAge,num_pipeline__Density,num_pipeline__ClaimFreq,power_pipeline__Power,other_cat_pipeline__Brand_Fiat,other_cat_pipeline__Brand_Japanese (except Nissan) or Korean,"other_cat_pipeline__Brand_Mercedes, Chrysler or BMW",...,other_cat_pipeline__Region_Aquitaine,other_cat_pipeline__Region_Basse-Normandie,other_cat_pipeline__Region_Bretagne,other_cat_pipeline__Region_Centre,other_cat_pipeline__Region_Haute-Normandie,other_cat_pipeline__Region_Ile-de-France,other_cat_pipeline__Region_Limousin,other_cat_pipeline__Region_Nord-Pas-de-Calais,other_cat_pipeline__Region_Pays-de-la-Loire,other_cat_pipeline__Region_Poitou-Charentes
0,0.00,0.240163,0.07,0.407407,0.152826,0.000000,0.181818,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.00,0.501829,0.13,0.358025,0.004667,0.000000,0.272727,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.25,0.199907,0.09,0.333333,1.000000,0.006849,0.090909,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.00,0.290483,0.04,0.172840,0.029632,0.000000,0.090909,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.00,0.260291,0.11,0.111111,0.018631,0.000000,0.181818,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [157]:
X_test.head()

,num_pipeline__ClaimNb,num_pipeline__Exposure,num_pipeline__CarAge,num_pipeline__DriverAge,num_pipeline__Density,num_pipeline__ClaimFreq,power_pipeline__Power,other_cat_pipeline__Brand_Fiat,other_cat_pipeline__Brand_Japanese (except Nissan) or Korean,"other_cat_pipeline__Brand_Mercedes, Chrysler or BMW",...,other_cat_pipeline__Region_Aquitaine,other_cat_pipeline__Region_Basse-Normandie,other_cat_pipeline__Region_Bretagne,other_cat_pipeline__Region_Centre,other_cat_pipeline__Region_Haute-Normandie,other_cat_pipeline__Region_Ile-de-France,other_cat_pipeline__Region_Limousin,other_cat_pipeline__Region_Nord-Pas-de-Calais,other_cat_pipeline__Region_Pays-de-la-Loire,other_cat_pipeline__Region_Poitou-Charentes
0,0.0,0.084170,0.11,0.407407,0.150270,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.501829,0.09,0.098765,0.001630,0.0,0.090909,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.381060,0.05,0.197531,0.142788,0.0,0.090909,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.501829,0.13,0.345679,0.010519,0.0,0.454545,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.335771,0.10,0.123457,0.025002,0.0,0.090909,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [158]:
len(X_train.columns)

26

Lasso Regression:

Lasso: This is a type of linear regression that includes a regularization term. The regularization term helps to prevent overfitting by penalizing large coefficients, effectively setting some of them to zero. This is useful for feature selection because it automatically excludes less important features.

Parameters:

alpha=5e-5: This sets the regularization strength. A smaller alpha means less regularization, and a larger alpha means more regularization. Here, 5e-5 is a very small value, indicating light regularization. This means the model will only slightly penalize large coefficients.

random_state=1: This ensures reproducibility. By setting a seed (in this case, 1), you ensure that the results are the same every time you run the code. This is useful for debugging and comparing models.

max_iter=1e+6: This sets the maximum number of iterations the algorithm will run to find the optimal solution. 1e+6 is a large number (1,000,000), ensuring that the algorithm has plenty of opportunities to converge to a solution.

Fitting the Model:

.fit(X_train_scale, y_train): This trains the Lasso regression model using the provided training data.
X_train_scale: These are the input features for training, usually scaled to ensure all features contribute equally to the model.
y_train: These are the target values corresponding to the input features. The model learns the relationship between X_train_scale and y_train during training.

In [159]:
from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel
import pandas as pd

# Establish the Lasso (L1) Regularisation model that will perform feature selection.
lasso = Lasso(alpha=1e-4, random_state=1, max_iter=1000).fit(X_train, y_train)
model = SelectFromModel(lasso, prefit=True)

# Transform the training data to keep only selected features
X_train_l1 = model.transform(X_train)

# Transform the test data in the same way
X_test_l1 = model.transform(X_test)

# Get the mask of selected features
selected_mask = model.get_support()

# Get the selected feature names
selected_feature_names = X_train.columns[selected_mask]

c:\Users\LENOVO\Downloads\Ineuron\MLEndToEnd\MlEndtoEnd\venv\lib\site-packages\scikit_learn-1.5.0-py3.9-win-amd64.egg\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.325e+12, tolerance: 7.045e+08
  model = cd_fast.enet_coordinate_descent(
c:\Users\LENOVO\Downloads\Ineuron\MLEndToEnd\MlEndtoEnd\venv\lib\site-packages\scikit_learn-1.5.0-py3.9-win-amd64.egg\sklearn\base.py:486: UserWarning: X has feature names, but SelectFromModel was fitted without feature names
  warnings.warn(
c:\Users\LENOVO\Downloads\Ineuron\MLEndToEnd\MlEndtoEnd\venv\lib\site-packages\scikit_learn-1.5.0-py3.9-win-amd64.egg\sklearn\base.py:486: UserWarning: X has feature names, but SelectFromModel was fitted without feature names
  warnings.warn(

In [160]:
# Get the mask of selected features
selected_mask = model.get_support()

In [161]:

# Get the selected feature names
selected_feature_names = X_train.columns[selected_mask]

In [162]:
print("Selected Features:")
print(selected_feature_names)

Selected Features:
Index(['num_pipeline__ClaimNb', 'num_pipeline__Exposure',
       'num_pipeline__CarAge', 'num_pipeline__DriverAge',
       'num_pipeline__Density', 'num_pipeline__ClaimFreq',
       'power_pipeline__Power', 'other_cat_pipeline__Brand_Fiat',
       'other_cat_pipeline__Brand_Japanese (except Nissan) or Korean',
       'other_cat_pipeline__Brand_Mercedes, Chrysler or BMW',
       'other_cat_pipeline__Brand_Opel, General Motors or Ford',
       'other_cat_pipeline__Brand_Renault, Nissan or Citroen',
       'other_cat_pipeline__Brand_Volkswagen, Audi, Skoda or Seat',
       'other_cat_pipeline__Brand_other', 'other_cat_pipeline__Gas_Diesel',
       'other_cat_pipeline__Region_Aquitaine',
       'other_cat_pipeline__Region_Basse-Normandie',
       'other_cat_pipeline__Region_Bretagne',
       'other_cat_pipeline__Region_Centre',
       'other_cat_pipeline__Region_Haute-Normandie',
       'other_cat_pipeline__Region_Ile-de-France',
       'other_cat_pipeline__Region_Limousin',
       'other_cat_pipeline__Region_Nord-Pas-de-Calais',
       'other_cat_pipeline__Region_Pays-de-la-Loire',
       'other_cat_pipeline__Region_Poitou-Charentes'],
      dtype='object')

In [163]:
# Create DataFrames for the selected features
X_train = pd.DataFrame(X_train_l1, index=X_train.index, columns=selected_feature_names)
X_test = pd.DataFrame(X_test_l1, index=X_test.index, columns=selected_feature_names)

In [164]:
len(X_train.columns)

25

In [165]:
X_train.head()

,num_pipeline__ClaimNb,num_pipeline__Exposure,num_pipeline__CarAge,num_pipeline__DriverAge,num_pipeline__Density,num_pipeline__ClaimFreq,power_pipeline__Power,other_cat_pipeline__Brand_Fiat,other_cat_pipeline__Brand_Japanese (except Nissan) or Korean,"other_cat_pipeline__Brand_Mercedes, Chrysler or BMW",...,other_cat_pipeline__Region_Aquitaine,other_cat_pipeline__Region_Basse-Normandie,other_cat_pipeline__Region_Bretagne,other_cat_pipeline__Region_Centre,other_cat_pipeline__Region_Haute-Normandie,other_cat_pipeline__Region_Ile-de-France,other_cat_pipeline__Region_Limousin,other_cat_pipeline__Region_Nord-Pas-de-Calais,other_cat_pipeline__Region_Pays-de-la-Loire,other_cat_pipeline__Region_Poitou-Charentes
0,0.00,0.240163,0.07,0.407407,0.152826,0.000000,0.181818,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.00,0.501829,0.13,0.358025,0.004667,0.000000,0.272727,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.25,0.199907,0.09,0.333333,1.000000,0.006849,0.090909,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.00,0.290483,0.04,0.172840,0.029632,0.000000,0.090909,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.00,0.260291,0.11,0.111111,0.018631,0.000000,0.181818,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [171]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso,ElasticNet
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor

import numpy as np

In [172]:
model={'Random Forest':RandomForestRegressor(),'LR':LinearRegression(),'DT':DecisionTreeRegressor(min_samples_leaf= 1, min_samples_split=5),
       'XGB':XGBRegressor(n_estimators=40, learning_rate=0.01, random_state=1)}

In [175]:
def eval_metrics(actual, pred):
    rmse = np.sqrt(mean_squared_error(actual, pred))
    mae = mean_absolute_error(actual, pred)
    r2 = r2_score(actual, pred)
    return mae

In [178]:
for m in range(len(list(model))):
    mod=list(model.values())[m]
    mod.fit(X_train,y_train)
    prediction=mod.predict(X_test)
    MAE=eval_metrics(y_test,prediction)
    print("Model performance:",mod)
  
    print("MAE",MAE)
    print("========================")

Model performance: RandomForestRegressor()
MAE 95.62498422965528
========================
Model performance: LinearRegression()
MAE 107.14262440399835
========================
Model performance: DecisionTreeRegressor(min_samples_split=5)
MAE 86.62646428830749
========================
Model performance: XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.01, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=40, n_jobs=None,
             num_parallel_tree=None, random_state=1, ...)
MAE 111.31379638766234
========================